### ISSUE TITLE
Add RemoteSwingLibrary to Maven Central

### ISSUE THREAD

**Issue by jussimalinen** [robotframework/remoteswinglibrary#14]
Adding this to maven central should not be too difficult.

**Comment by lindmik** [comment]
Any update on this? A non-fat Jar version in Maven Central would be highly appreciated.

**Comment by WojtekKowaluk** [comment]
http://search.maven.org/#artifactdetails%7Corg.robotframework%7Cremoteswinglibrary%7C2.1.2%7Cjar
I put it there, but it is regular "fat" version. I put it there because somebody requested they want to download RSL by maven. Actually same pom file generates both "slim" and "fat" version, so I am not sure how it should look on maven. I'm open for suggestions.
