### ISSUE TITLE
[Errno 10061] No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by javier-jimenez** [robotframework/remoteswinglibrary#31]
If the Swing applications calls System.exit() (as many applications do after logging out) the communication is lost and I start getting this errors:

20151022 10:50:04.964 :  FAIL : Connection to remote server broken: [Errno 10061] No connection could be made because the target machine actively refused it

This is a simple test where the logout button is being pressed (the logout method clears stuff and then calls System.exit() at the end). However It seems that the remote server is stopping too? I had this same problem with Jython (jybot was dying when the application closed down), that's why I wanted to give a try to the remote lib.

Any recommendations for this? Thanks!

**Comment by javier-jimenez** [comment]
Forgot to mention that I'm using right now the "Ensure Application Should Close" keyword along with my logout keyword however if the application closes really the last keywords (like looking for the Main Window to ensure it's closed) will throw this error.

**Comment by mihaiparvu** [comment]
I've created a small application that also does `System.exit()` at a press of a button, to help me better analyze this behavior. 

In the keyword documentation of the `Ensure Application Should Close`, it says that closing the application might break the remote connection. This is exactly what happens in your case. Your application is breaking the remote connection and there is nothing the RemoteSwingLibrary can do about it. So, the additional check for the main window being closed cannot be done using RemoteSwingLibrary, because there is no connection anymore. As an alternative, I would suggest that you check for the `Connection broken...` error message or use a different library to check that the java process was closed.

From my point of view, RemoteSwingLibrary is behaving as is should. Please let me know if I missed something or you have other suggestions.
